# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatgpt-cli" do
  version "2.5.1"

  on_macos do
    on_arm do
      sha256 "76a3f929c7d3f1b8e534dd23275e566bb7c451d77ddbfba704a7115b7453d868"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_darwin_arm64"
      binary "chatgpt-cli_darwin_arm64", target: "chatgpt-cli"
    end
    on_intel do
      sha256 "e9950c3c9a1a4e3650e44a81c06f72b5f60d68c9033cc766346b2ed2f878d7b2"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_darwin_x86_64"
      binary "chatgpt-cli_darwin_x86_64", target: "chatgpt-cli"
    end
  end
  on_linux do
    on_arm do
      sha256 "121c84b4b3841ae3834b729daa8ebe859d6d4bafcfc05a073be87e50957895e3"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_linux_arm64"
      binary "chatgpt-cli_linux_arm64", target: "chatgpt-cli"
    end
    on_intel do
      sha256 "a535115fed44356916d1320555cdddf9d7dde6d4edb9ad97831ba57b7ad1d8e5"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_linux_x86_64"
      binary "chatgpt-cli_linux_x86_64", target: "chatgpt-cli"
    end
  end

  name "chatgpt-cli"
  desc "ChatGPT Command-Line Interface"
  homepage "https://github.com/duanemay/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
     arch = Hardware::CPU.arch
     binary_name = if arch == :arm64
       "chatgpt-cli_darwin_arm64"
      else
        "chatgpt-cli_darwin_x86_64"
      end
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required
end
