# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatgpt-cli" do
  version "2.4.3"

  on_macos do
    on_intel do
      sha256 "cc4ad9cd26d0d5eab5671ebfdc3d2a9b6f703ce585cb45da2aa6339fc0e93fa0"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_darwin_x86_64"
      binary "chatgpt-cli_darwin_x86_64", target: "chatgpt-cli"
    end
    on_arm do
      sha256 "73179263d1606e381819545e5b9ba69d4621288cb0057190d3f90ba013e09c5d"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_darwin_arm64"
      binary "chatgpt-cli_darwin_arm64", target: "chatgpt-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "44226a4304c1e72bd61a7be1c03273141c4630f3320b57d9d50f621c0ac97229"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_linux_x86_64"
      binary "chatgpt-cli_linux_x86_64", target: "chatgpt-cli"
    end
    on_arm do
      sha256 "5b08414c83253984b73b25aacb4846cdf18407f35a4e34bcc5eabe4cbb8ebcf6"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_linux_arm64"
      binary "chatgpt-cli_linux_arm64", target: "chatgpt-cli"
    end
  end

  name "chatgpt-cli"
  desc "ChatGPT Command-Line Interface"
  homepage "https://github.com/duanemay/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
     arch = Hardware::CPU.arch
     binary_name = if arch == :arm64
       "chatgpt-cli_darwin_arm64"
      else
        "chatgpt-cli_darwin_x86_64"
      end
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

end
