# This file was generated by GoReleaser. DO NOT EDIT.
cask "chatgpt-cli" do
  version "2.4.11"

  on_macos do
    on_intel do
      sha256 "03ef7a32c9d284ecafffacf13710e42a303f73fbccbe7939ee29803548a9c8cb"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_darwin_x86_64"
      binary "chatgpt-cli_darwin_x86_64", target: "chatgpt-cli"
    end
    on_arm do
      sha256 "4b214e6f634f8ec6327e589acd1e0d18bba38133af1113e55e56e53d12c13ef9"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_darwin_arm64"
      binary "chatgpt-cli_darwin_arm64", target: "chatgpt-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "c62155b5dd2e0233ce1a1f4d6d923bcfaf5ac911066ed3c6c15fa94591f6c9d0"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_linux_x86_64"
      binary "chatgpt-cli_linux_x86_64", target: "chatgpt-cli"
    end
    on_arm do
      sha256 "147cc4fe0eb84b37a94b6bf92cfb621c2fc81e4374984d410371b9e1387d432e"
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v#{version}/chatgpt-cli_linux_arm64"
      binary "chatgpt-cli_linux_arm64", target: "chatgpt-cli"
    end
  end

  name "chatgpt-cli"
  desc "ChatGPT Command-Line Interface"
  homepage "https://github.com/duanemay/homebrew-tap"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
     arch = Hardware::CPU.arch
     binary_name = if arch == :arm64
       "chatgpt-cli_darwin_arm64"
      else
        "chatgpt-cli_darwin_x86_64"
      end
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

end
