# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptCli < Formula
  desc "Recursively expand archives containing other archives"
  homepage "https://github.com/duanemay/homebrew-tap"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v0.0.1/chatgpt-cli_Darwin_arm64.tar.gz"
      sha256 "914446064bd7f7ecdd81a07017722f772c114697bc9d1729010656168d98df69"

      def install
        bin.install "chatgpt-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v0.0.1/chatgpt-cli_Darwin_x86_64.tar.gz"
      sha256 "0dbfa4536f19004e460cc8e563ab14cb7be5b251456e8b243e2104084a6be6ac"

      def install
        bin.install "chatgpt-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v0.0.1/chatgpt-cli_Linux_arm64.tar.gz"
      sha256 "25af514bd22a2e160f63f6eedb7367ffab24d7e29499c759b2d4e2e8c2dc758c"

      def install
        bin.install "chatgpt-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v0.0.1/chatgpt-cli_Linux_x86_64.tar.gz"
      sha256 "044685af40c7ab2a7ffe6ccbb09ae83aee2e127ae5f089e80d7babb8b9920087"

      def install
        bin.install "chatgpt-cli"
      end
    end
  end
end
