# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptCli < Formula
  desc "Recursively expand archives containing other archives"
  homepage "https://github.com/duanemay/homebrew-tap"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v1.3.0/chatgpt-cli_Darwin_arm64.tar.gz"
      sha256 "04105b22b7da72e45a0afaff5f6f4d74166f7bbc60b8c094e6c57d050febf13a"

      def install
        bin.install "chatgpt-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v1.3.0/chatgpt-cli_Darwin_x86_64.tar.gz"
      sha256 "4e6210b17fcea1c9d9cbd3bb5ffd8d840645e06bae9b1affee27a7f63a4b33ed"

      def install
        bin.install "chatgpt-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v1.3.0/chatgpt-cli_Linux_arm64.tar.gz"
      sha256 "903f6cd5098e4dabd31827d938acf3772b4fe653cbbad36d90942e4227ba282b"

      def install
        bin.install "chatgpt-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/duanemay/chatgpt-cli/releases/download/v1.3.0/chatgpt-cli_Linux_x86_64.tar.gz"
      sha256 "8cac8721049be8dd133b2f6afa10a404abd6f20691338867a824fe8931a74ad9"

      def install
        bin.install "chatgpt-cli"
      end
    end
  end
end
